/*
<MODULE_CONTRACT>
<purpose>Kernel configuration for {{APP_NAME}} — declares modules and pipelines.</purpose>
<non-goals>
  <item>Do not add business logic or runtime behavior here.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>Generated by kernel.wire (RFC-0078).</item>
</CHANGE_SUMMARY>
*/
import { defineKernelConfig } from "@warpgogol/werkstatt-engine/kernel/types";
import {
  SITES_CHECK_PIPELINE,
  STANDARD_COMPASS_PIPELINE,
  SITES_BUILD_PREPARE_PIPELINE,
  SITES_BUILD_PREPARE_DEV_PIPELINE,
  SITES_BUILD_CHECK_PIPELINE,
  SITES_BUILD_POST_PIPELINE,
} from "@warpgogol/werkstatt-site/checks/pipelines";
import { STANDARD_INTEGRITY_PIPELINE } from "@warpgogol/werkstatt-engine/integrity";

// moduleLoaders: each module is loaded lazily via dynamic import(), so that
// tsImport of this config file does not transitively import all module
// packages. The kernel runtime uses buildRegistryForModule() to load only
// the module that owns the requested command (manifest-driven), or
// buildRegistry() to load all modules when needed.
export default defineKernelConfig({
  name: "{{APP_NAME}}",
  description: "{{APP_NAME}} Astro site OS",
  moduleLoaders: {
    check: async () => (await import("./modules/check.module")).checkModule,
    service: async () => (await import("./modules/service.module")).serviceModule,
    deploy: async () => (await import("./modules/deploy.module")).deployModule,
    integrity: async () => (await import("./modules/integrity.module")).integrityModule,
    changelog: async () => (await import("./modules/changelog.module")).changelogModule,
    rfc: async () => (await import("@warpgogol/forge")).forgeRfcModule,
    workflow: async () => (await import("@warpgogol/forge")).forgeWorkflowModule,
    compass: async () => (await import("@warpgogol/forge")).forgeCompassModule,
    naming: async () => (await import("@warpgogol/forge")).forgeNamingModule,
    werkstatt: async () => (await import("@warpgogol/forge")).forgeWerkstattModule,
    "change-impact": async () => (await import("@warpgogol/werkstatt-engine/kernel")).changeImpactModule,
    bordbuch: async () =>
      (await import("@warpgogol/werkstatt-engine/handoff")).createBordbuchModule(),
    nachweis: async () =>
      (await import("@warpgogol/werkstatt-engine/handoff")).createNachweisModule(),
    sichtpass: async () =>
      (await import("@warpgogol/werkstatt-engine/sichtpass-module")).createSichtpassModule(),
    dns: async () => (await import("@warpgogol/werkstatt-engine/dns-module")).createDnsModule(),
    onboarding: async () =>
      (await import("@warpgogol/werkstatt-site/onboarding")).createOnboardingModule(),
    testing: async () =>
      (await import("@warpgogol/werkstatt-site/testing/module")).createTestingModule(),
  },
  pipelines: {
    "build.prepare": [...SITES_BUILD_PREPARE_PIPELINE],
    "build.prepare.dev": [...SITES_BUILD_PREPARE_DEV_PIPELINE],
    "build.check": [...SITES_BUILD_CHECK_PIPELINE],
    "build.post": [...SITES_BUILD_POST_PIPELINE],
    check: [...SITES_CHECK_PIPELINE],
    compass: [...STANDARD_COMPASS_PIPELINE],
    "integrity.release": [...STANDARD_INTEGRITY_PIPELINE],
  },
});
