/*
<MODULE_CONTRACT>
<purpose>App runtime helpers requiring an app-scoped kernel context.</purpose>
<non-goals>
  <item>Do not implement Astro path resolution here — delegate to site-kernel-astro.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>Generated by kernel.wire (RFC-0078).</item>
</CHANGE_SUMMARY>
*/
import { requireAstroSitePaths } from "@warpgogol/werkstatt-site/paths";
import type { DiscoveredSiteWorkspace, KernelRuntimeContext } from "@warpgogol/werkstatt-engine/kernel";

export function requireApp(context: KernelRuntimeContext): DiscoveredSiteWorkspace {
  if (!context.site) throw new Error("This command requires an app-scoped runtime context.");
  return context.site;
}

export function requireAppAstroPaths(context: KernelRuntimeContext) {
  return requireAstroSitePaths(context);
}
