/*
<MODULE_CONTRACT>
<purpose>Re-export changelog commands from @warpgogol/site-kernel-changelog.</purpose>
<non-goals>
  <item>Do not implement logic locally — this file is a thin proxy.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>Generated by kernel.wire (RFC-0078).</item>
</CHANGE_SUMMARY>
*/
export {
  runChangelogGenerate,
  runChangelogRebuildIndex,
  runChangelogBackfill,
} from "@warpgogol/werkstatt-engine/changelog";
