/*
<MODULE_CONTRACT>
<purpose>Check runtime type placeholder — ensures kernel types are available in app tooling.</purpose>
<non-goals>
  <item>Do not implement logic here — this file is a type placeholder.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>Generated by kernel.wire (RFC-0078).</item>
</CHANGE_SUMMARY>
*/
import type { KernelCommandInput, KernelCommandResult, KernelRuntimeContext } from "@warpgogol/werkstatt-engine/kernel";
void ({} as { input?: KernelCommandInput; result?: KernelCommandResult; context?: KernelRuntimeContext });
