/*
<MODULE_CONTRACT>
<purpose>Re-export runtime commands from {{PACKAGE_NAME}}.</purpose>
<non-goals>
  <item>Do not implement logic locally — this file is a thin proxy.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>Generated by kernel.wire (RFC-0078).</item>
</CHANGE_SUMMARY>
*/
export {
  {{EXPORTS_LIST}}
} from "{{PACKAGE_NAME}}";
