/*
<MODULE_CONTRACT>
<purpose>Defines the structure for exporting icon components, ensuring a consistent interface for consumers.</purpose>
<non-goals>
  <item>Do not implement icon rendering or display logic.</item>
  <item>Do not manage icon styling or theming details.</item>
  <item>Do not handle raw asset parsing or storage.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>Enhance Compass scaffolding to clarify the role and responsibilities of icon exports.</item>
</CHANGE_SUMMARY>
*/

// Auto-generated by werkstatt icons.generate command
// Do not edit manually

{{EXPORTS_LIST}}
