/*
<MODULE_CONTRACT>
<purpose>Defines the structure for exporting icon components, ensuring a consistent interface for consumers.</purpose>
<non-goals>
  <item>Do not implement icon rendering or display logic.</item>
  <item>Do not manage icon styling or theming details.</item>
  <item>Do not handle raw asset parsing or storage.</item>
</non-goals>
</MODULE_CONTRACT>
<KEY_DECISIONS>
  <item>TODO: record current design decisions</item>
</KEY_DECISIONS>
<CHANGE_SUMMARY>
  <item>RFC-1097: step 6 — compass.migrate codemod run

Mechanical v1 to v2 header migration across the workspace: 942 files rewritten — CHANGE_SUMMARY windows collapsed into <history>, forbidden v1 blocks stripped, KEY_DECISIONS seeded from @ai-invariant comments (5 files) or TODO placeholders (103 files), blocks reordered to canonical order.</item>
</CHANGE_SUMMARY>
*/

// Auto-generated by werkstatt icons.generate command
// Do not edit manually

{{EXPORTS_LIST}}
