/*
<MODULE_CONTRACT>
<purpose>Changelog module registering changelog generation commands.</purpose>
<non-goals>
  <item>Do not implement changelog logic here — delegate to site-kernel-changelog.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>Generated by kernel.wire (RFC-0078).</item>
</CHANGE_SUMMARY>
*/
import type { KernelModule } from "@warpgogol/werkstatt-engine/kernel";
import {
  runChangelogGenerate,
  runChangelogRebuildIndex,
  runChangelogBackfill,
} from "./../runtime/changelog";

const changelogFlags = {
  provider: {
    kind: "string",
    description: "LLM provider override: openai or anthropic.",
  },
  model: {
    kind: "string",
    description: "LLM model override for changelog generation.",
  },
  mode: {
    kind: "string",
    description: "Release cadence mode: weekly or monthly.",
  },
  day: {
    kind: "string",
    description: "Release day number used by the changelog cadence check.",
  },
  tz: {
    kind: "string",
    description: "Timezone used by release-day calculations.",
  },
} as const;

export const changelogModule: KernelModule = {
  name: "changelog",
  version: "0.1.0",
  register(registry) {
    registry.registerCommand({
      name: "changelog.generate",
      description: "Generate the changelog.",
      scope: "app",
      mutatesState: true,
      supportsAllSites: true,
      cacheable: false,
      writes: [
        "<app>/CHANGELOG.md",
        "<app>/changelogs/**",
        "<app>/.changelog-system/state.json",
        "<app>/package.json",
        ".changelog-system/cache/**",
      ],
      reads: ["<app>/src/content/**", "<app>/package.json"],
      flags: { ...changelogFlags },
      execute: runChangelogGenerate,
    });
    registry.registerCommand({
      name: "changelog.rebuild-index",
      description: "Rebuild changelog index.",
      scope: "app",
      mutatesState: true,
      cacheable: false,
      writes: ["<app>/CHANGELOG.md"],
      reads: ["<app>/CHANGELOG.md", "<app>/changelogs/**"],
      flags: { ...changelogFlags },
      execute: runChangelogRebuildIndex,
    });
    registry.registerCommand({
      name: "changelog.backfill",
      description: "Backfill changelog history.",
      scope: "app",
      mutatesState: true,
      cacheable: false,
      writes: ["<app>/CHANGELOG.md", "<app>/changelogs/**", ".changelog-system/cache/**"],
      reads: ["<app>/src/content/**", "<app>/package.json"],
      flags: {
        ...changelogFlags,
        start: { kind: "string", required: true, description: "Backfill start date (YYYY-MM-DD)." },
        end: { kind: "string", required: true, description: "Backfill end date (YYYY-MM-DD)." },
      },
      execute: runChangelogBackfill,
    });
  },
};
