/*
<MODULE_CONTRACT>
<purpose>Deploy module registering client export command.</purpose>
<non-goals>
  <item>Do not implement export logic here — delegate to site-kernel-deploy.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>Generated by kernel.wire (RFC-0078).</item>
</CHANGE_SUMMARY>
*/
import type { KernelModule } from "@warpgogol/werkstatt-engine/kernel";
import { runClientExport } from "./../runtime/client-export";
import type { ModuleExport } from "../runtime/desired-state.ts";

export const deployModule: ModuleExport = {
  name: "deploy",
  version: "0.1.0",
    declarations: [],
  commands: [
    {
      name: "client.export",
      description: "Export the current app for client delivery.",
      scope: "app",
      mutatesState: true,
      cacheable: false,
      writes: ["../clients/<app>/**"],
      reads: ["<app>/dist/**"],
      flags: {},
      execute: runClientExport,
    }
  ],
  pipelines: [

  ]};
