/*
<MODULE_CONTRACT>
<purpose>Integrity module registering integrity tracking and signing commands.</purpose>
<non-goals>
  <item>Do not implement integrity logic here — delegate to site-kernel-integrity.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>Generated by kernel.wire (RFC-0078).</item>
</CHANGE_SUMMARY>
*/
import type { KernelModule } from "@warpgogol/werkstatt-engine/kernel";
import {
import type { ModuleExport } from "../runtime/desired-state.ts";
  runIntegrityBackfillRevisions,
  runIntegrityBuildRecord,
  runIntegrityGenerateSigningKeypair,
  runIntegrityInit,
  runIntegritySign,
  runIntegrityUpdate,
  runIntegrityVerify,
  runIntegrityVerifyRelease,
} from "./../runtime/integrity";

export const integrityModule: ModuleExport = {
  name: "integrity",
  version: "0.1.0",
    declarations: [],
  commands: [
    {
      name: "integrity.init",
      description: "Initialize integrity tracking.",
      scope: "app",
      mutatesState: true,
      cacheable: false,
      writes: ["<app>/.integrity/**"],
      reads: ["<app>/.integrity/**"],
      flags: {},
      execute: runIntegrityInit,
    },
    {
      name: "integrity.update",
      description: "Update integrity manifests.",
      scope: "app",
      mutatesState: true,
      cacheable: false,
      writes: ["<app>/.integrity/**"],
      reads: ["<app>/.integrity/**"],
      flags: {},
      execute: runIntegrityUpdate,
    },
    { name: "integrity.verify", description: "Verify integrity manifests.", scope: "app", flags: {}, reads: ["<app>/.integrity/**"], execute: runIntegrityVerify },
    {
      name: "integrity.build-record",
      description: "Record build outputs.",
      scope: "app",
      mutatesState: true,
      cacheable: false,
      writes: ["<app>/.integrity/build/latest/**"],
      reads: ["<app>/dist/**"],
      flags: {},
      execute: runIntegrityBuildRecord,
    },
    {
      name: "integrity.sign",
      description: "Sign integrity artifacts.",
      scope: "app",
      mutatesState: true,
      cacheable: false,
      writes: ["<app>/.integrity/build/latest/**"],
      reads: ["<app>/.integrity/**"],
      flags: {},
      execute: runIntegritySign,
    },
    { name: "integrity.verify-release", description: "Verify release signatures.", scope: "app", requiresNetwork: true, flags: {}, reads: ["<app>/.integrity/**"], cacheable: false, execute: runIntegrityVerifyRelease },
    {
      name: "integrity.keys.generate",
      modulePath: "tools/modules/integrity.module.ts",
      description: "Generate integrity signing keys.",
      scope: "app",
      mutatesState: true,
      cacheable: false,
      writes: ["<app>/.integrity/keys/**", "<app>/public/studio.public.pem"],
      generates: [
        { path: ".integrity/keys/private.pem", phase: "build.prepare", conditional: true },
        { path: "public/studio.public.pem", phase: "build.prepare", conditional: true },
      ],
      flags: {},
      execute: runIntegrityGenerateSigningKeypair,
    },
    {
      name: "integrity.backfill-revisions",
      description: "Backfill integrity revision counters.",
      scope: "app",
      mutatesState: true,
      cacheable: false,
      writes: ["<app>/.integrity/**"],
      reads: ["<app>/.integrity/**"],
      flags: {},
      execute: runIntegrityBackfillRevisions,
    }
  ],
  pipelines: [

  ]};
