/*
<MODULE_CONTRACT>
<purpose>Pipelines module for {{APP_NAME}} — declares site-level build and check pipelines as ModuleExport.pipelines (RFC-1038).</purpose>
<non-goals>
  <item>Do not implement commands here — only pipeline declarations.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>Generated by kernel.wire (RFC-0078). RFC-1038: moved config-level pipelines into ModuleExport.pipelines.</item>
</CHANGE_SUMMARY>
*/
import type { ModuleExport } from "@warpgogol/werkstatt-engine/runtime/desired-state";
import type { KernelPipelineStep } from "@warpgogol/werkstatt-engine/kernel";
import {
  SITES_CHECK_PIPELINE,
  STANDARD_COMPASS_PIPELINE,
  SITES_BUILD_PREPARE_PIPELINE,
  SITES_BUILD_PREPARE_DEV_PIPELINE,
  SITES_BUILD_CHECK_PIPELINE,
  SITES_BUILD_POST_PIPELINE,
} from "@warpgogol/werkstatt-site/checks/pipelines";
import { STANDARD_INTEGRITY_PIPELINE } from "@warpgogol/werkstatt-engine/integrity";

const pipelines: { name: string; steps: KernelPipelineStep[] }[] = [
  { name: "build.prepare", steps: [...SITES_BUILD_PREPARE_PIPELINE] },
  { name: "build.prepare.dev", steps: [...SITES_BUILD_PREPARE_DEV_PIPELINE] },
  { name: "build.check", steps: [...SITES_BUILD_CHECK_PIPELINE] },
  { name: "build.post", steps: [...SITES_BUILD_POST_PIPELINE] },
  { name: "check", steps: [...SITES_CHECK_PIPELINE] },
  { name: "compass", steps: [...STANDARD_COMPASS_PIPELINE] },
  { name: "integrity.release", steps: [...STANDARD_INTEGRITY_PIPELINE] },
];

export const pipelinesModule: ModuleExport = {
  name: "pipelines",
  version: "0.1.0",
  declarations: [],
  commands: [],
  pipelines,
};
