/*
<MODULE_CONTRACT>
<purpose>Service module registering icon, open-source, material credit generation, and metadata write commands.</purpose>
<non-goals>
  <item>Do not implement generation logic here — delegate to site-kernel-codegen.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>Generated by kernel.wire (RFC-0078).</item>
  <item>RFC-0226: added material.metadata.write command.</item>
  <item>RFC-0527: added content.ref-index.generate command.</item>
  <item>RFC-0528: updated material.metadata.write description, writes, and reads for manifest-based discovery.</item>
  <item>RFC-0529: added content.ref-migrate command.</item>
  <item>RFC-0570: added content.formula.migrate command.</item>
</CHANGE_SUMMARY>
*/
import type { KernelModule } from "@warpgogol/werkstatt-engine/kernel";
import {
  runCleanIcons,
  runGenerateIcons,
  runGenerateMaterialCreditsPage,
  runGenerateOpenSourcePage,
  runMaterialMetadataWrite,
  runContentRefIndexGenerate,
  runContentRefMigrate,
  runContentFormulaMigrate,
} from "@warpgogol/werkstatt-site/codegen";

export const serviceModule: KernelModule = {
  name: "service",
  version: "0.1.0",
  register(registry) {
    registry.registerCommand({
      name: "icons.generate",
      modulePath: "tools/modules/service.module.ts",
      description: "Generate Astro icon wrappers from icon JSON assets.",
      scope: "app",
      mutatesState: true,
      cacheable: false,
      writes: ["<app>/src/components/icons/generated/**"],
      reads: ["<app>/src/content/system.md"],
      flags: {},
      generates: [{ path: "src/components/icons/generated/**", phase: "build.prepare", conditional: true }],
      execute: runGenerateIcons,
    });
    registry.registerCommand({
      name: "icons.clean",
      description: "Delete generated Astro icon wrappers.",
      scope: "app",
      mutatesState: true,
      cacheable: false,
      writes: ["<app>/src/components/icons/generated/**"],
      reads: ["<app>/src/components/icons/generated/**"],
      flags: {},
      execute: runCleanIcons,
    });
    registry.registerCommand({
      name: "open-source.generate",
      modulePath: "tools/modules/service.module.ts",
      description: "Generate the open-source disclosure page from production dependencies.",
      scope: "app",
      mutatesState: true,
      cacheable: false,
      writes: [
        "<app>/src/content/pages/{lang}/open-source.md",
        "<app>/.cache/open-source.fingerprint",
      ],
      reads: ["<app>/package.json"],
      generates: [{ path: "src/content/pages/{lang}/open-source.md", phase: "build.prepare", conditional: true }],
      flags: {
        "show-versions": {
          kind: "boolean",
          description: "Include dependency versions in the generated disclosure prose.",
        },
      },
      execute: runGenerateOpenSourcePage,
    });
    registry.registerCommand({
      name: "material.credits.generate",
      description: "Generate localized material credits pages from *.credits.yaml sidecars.",
      scope: "app",
      mutatesState: true,
      cacheable: false,
      writes: [
        "<app>/src/content/pages/{lang}/credits.md",
        "<app>/src/content/prose/{lang}/credits.md",
      ],
      reads: ["<app>/src/content/**/*.credits.yaml", "<app>/public/**/*.credits.yaml"],
      flags: {},
      execute: runGenerateMaterialCreditsPage,
    });
    registry.registerCommand({
      name: "material.metadata.write",
      description:
        "Write IPTC/XMP metadata (title, copyright, creator, artist, comment, WebStatement, encoder) into derived image/video variants from manifests. Uses MaterialCredit sidecars with content reference resolution and SemanticSiteProfile fallback. Gracefully skips when exiftool is unavailable (RFC-0528).",
      scope: "app",
      mutatesState: true,
      cacheable: false,
      writes: ["<app>/public/_img/**/*.webp", "<app>/public/_video/**"],
      reads: [
        "<app>/src/content/**/*.credits.yaml",
        "<app>/src/video-manifest.generated.yaml",
        "<app>/src/live-video-manifest.generated.yaml",
        "<app>/src/image-variants.generated.yaml",
        "<app>/src/content-ref-index.generated.yaml",
        "<app>/src/content/system.md",
      ],
      flags: {},
      execute: runMaterialMetadataWrite,
    });
    registry.registerCommand({
      name: "content.ref-index.generate",
      modulePath: "tools/modules/service.module.ts",
      description:
        "Scan src/content/ for .md files, parse frontmatter, and write src/content-ref-index.generated.yaml (RFC-0527).",
      scope: "app",
      mutatesState: true,
      cacheable: false,
      writes: ["<app>/src/content-ref-index.generated.yaml"],
      reads: ["<app>/src/content/**/*.md"],
      flags: {},
      generates: [{ path: "src/content-ref-index.generated.yaml", phase: "build.prepare" }],
      execute: runContentRefIndexGenerate,
    });
    registry.registerCommand({
      name: "content.ref-migrate",
      description:
        "Migrate brace-delimited {collection.file.field} references to braceless syntax in src/content/ (RFC-0529). Idempotent.",
      scope: "app",
      mutatesState: true,
      cacheable: false,
      writes: ["<app>/src/content/**/*.md", "<app>/src/content/**/*.yaml"],
      reads: ["<app>/src/content/**/*.md", "<app>/src/content/**/*.yaml"],
      flags: {},
      execute: runContentRefMigrate,
    });
    registry.registerCommand({
      name: "content.formula.migrate",
      description:
        "Convert hardcoded arithmetic patterns next to content references to =(...) formula syntax in src/content/ (RFC-0570). Manual command — not in any pipeline. Idempotent.",
      scope: "app",
      mutatesState: true,
      cacheable: false,
      writes: ["<app>/src/content/**/*.md"],
      reads: ["<app>/src/content/**/*.md"],
      flags: {},
      execute: runContentFormulaMigrate,
    });
  },
};
