/*
<MODULE_CONTRACT>
<purpose>RFC-0865: Shared helper for certification-gated deployment authorization. Loads gate decisions, calls authorizeDeployment(), and records deployment operation state.</purpose>
<non-goals>
  <item>Do not implement deployment adapter logic — that lives in adapter.ts and cloudflare-workers.ts.</item>
  <item>Do not implement certification evaluation — that lives in aggregation.ts.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
<item>RFC-0865: initial deploy authorization helper.</item>
<item>RFC-0866 fix: add resolveGateDecisionPath helper for conventional gate-decision path resolution.</item>
<item>RFC-0866 fix D-2: writeDeploymentEffectRecord accepts optional deploymentUrl for effect-record URL discovery.</item>
<item>Fix hardcoded systems-cache paths: writeDeploymentEffectRecord and resolveGateDecisionPath now accept cacheCloneDir directly. writeDeploymentEffectRecord commits+pushes to cache clone git after write.</item>
<item>RFC-0926: buildEffectRecord and writeDeploymentEffectRecord accept optional workerVersionId and releaseId for release-aware rollback.</item>
</CHANGE_SUMMARY>
*/

import fs from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { writeFileIfChanged } from "@warpgogol/werkstatt-engine/kernel";
import { cacheCloneCommit } from "../mission/mission-git-commit.ts";
import { gitExec } from "../werkstatt/git-exec.ts";
import type { Sha256Digest } from "../fingerprint/primitives.ts";
import { isSha256Digest, byteHashFile } from "../fingerprint/primitives.ts";
import type {
  GateDecisionV1,
  MainVerificationDecisionV1,
} from "../certification/contracts/decisions.ts";
import {
  gateDecisionV1Schema,
  mainVerificationDecisionV1Schema,
} from "../certification/contracts/decisions.ts";
import {
  authorizeDeployment,
  verifyMainPromotion,
  evaluateRollback,
  buildDeploymentEffectRecord,
  type CertificationGate,
  type DeploymentAuthorizationInputV1,
  type DeploymentAuthorizationOutcomeV1,
  type MainVerificationOutcomeV1,
  type RollbackEvaluationInputV1,
  type RollbackEvaluationOutcomeV1,
  type DeploymentEffectRecordV1,
} from "../certification/deployment/authority.ts";
import type { DeploymentOperationState } from "../certification/state-machine.ts";
import {
  createR2StorageAdapter,
  verifyStoredObject,
  type R2StorageConfig,
} from "../certification/storage/index.ts";

export function flagSite(input: { flags: Record<string, unknown> }): string | undefined {
  const v = input.flags["site"];
  if (typeof v === "string") return v;
  const sys = input.flags["system"];
  if (typeof sys === "string") return sys;
  return undefined;
}

export interface GateDecisionInput {
  gateDecisionPath: string;
  artifactHash: Sha256Digest;
  candidateId: string;
  gate: CertificationGate;
  durableSyncVerified: boolean;
  artifactReadinessVerified: boolean;
  forceRequested: boolean;
  skipRequested: boolean;
  waiverRequested: boolean;
  graceRequested: boolean;
}

export interface AuthorizeResult {
  ok: true;
  outcome: DeploymentAuthorizationOutcomeV1 & { ok: true };
  gateDecision: GateDecisionV1;
}

export interface AuthorizeFailure {
  ok: false;
  outcome: DeploymentAuthorizationOutcomeV1 & { ok: false };
  gateDecision: GateDecisionV1;
}

export type AuthorizeOutcome = AuthorizeResult | AuthorizeFailure;

export async function loadGateDecision(filePath: string): Promise<GateDecisionV1> {
  if (!existsSync(filePath)) {
    throw new Error(`[deploy] gate decision file not found: ${filePath}`);
  }
  const content = await fs.readFile(filePath, "utf8");
  const parsed = JSON.parse(content);
  const result = gateDecisionV1Schema.safeParse(parsed);
  if (!result.success) {
    throw new Error(
      `[deploy] invalid gate decision: ${result.error.issues.map((i) => i.message).join("; ")}`,
    );
  }
  return result.data;
}

export async function loadMainVerificationDecision(
  filePath: string,
): Promise<MainVerificationDecisionV1> {
  if (!existsSync(filePath)) {
    throw new Error(
      `[deploy] main verification decision file not found at ${filePath}. ` +
        `Run 'leitstand.certify --site <site> --release <release> --gate main' first — it generates ` +
        `the main-verification file. The expected path is gate-decisions/<release>-main-verification.json.`,
    );
  }
  const content = await fs.readFile(filePath, "utf8");
  const parsed = JSON.parse(content);
  const result = mainVerificationDecisionV1Schema.safeParse(parsed);
  if (!result.success) {
    throw new Error(
      `[deploy] invalid main verification decision: ${result.error.issues.map((i) => i.message).join("; ")}. ` +
        `Expected schema 'werkstatt/main-verification-decision@1'. ` +
        `Use the file from gate-decisions/<release>-main-verification.json (generated by leitstand.certify --gate main), ` +
        `not the gate-decision file.`,
    );
  }
  return result.data;
}

export async function resolveArtifactHash(
  artifactHashFlag: string | undefined,
  releaseDir: string | undefined,
): Promise<Sha256Digest> {
  if (artifactHashFlag && isSha256Digest(artifactHashFlag)) {
    return artifactHashFlag;
  }

  if (releaseDir && existsSync(releaseDir)) {
    const artifactPath = path.join(releaseDir, "artifact.tar.gz");
    if (existsSync(artifactPath)) {
      return await byteHashFile(artifactPath);
    }

    const releaseYamlPath = path.join(releaseDir, "release.yaml");
    if (existsSync(releaseYamlPath)) {
      try {
        const content = await fs.readFile(releaseYamlPath, "utf8");
        const match = content.match(/^distTreeHash:\s*(sha256:[a-f0-9]{64})\s*$/m);
        if (match && isSha256Digest(match[1])) {
          return match[1];
        }
      } catch {
        // release.yaml unreadable — fall through to error
      }
    }
  }

  throw new Error(
    "[deploy] artifact hash not provided and no artifact.tar.gz or release.yaml with distTreeHash found in release directory — use --artifact-hash or --release-dir",
  );
}

export async function authorizeAndDeploy(input: GateDecisionInput): Promise<AuthorizeOutcome> {
  const gateDecision = await loadGateDecision(input.gateDecisionPath);

  const authInput: DeploymentAuthorizationInputV1 = {
    candidateId: input.candidateId,
    gate: input.gate,
    gateDecision,
    durableSyncVerified: input.durableSyncVerified,
    artifactReadinessVerified: input.artifactReadinessVerified,
    artifactHash: input.artifactHash,
    forceRequested: input.forceRequested,
    skipRequested: input.skipRequested,
    waiverRequested: input.waiverRequested,
    graceRequested: input.graceRequested,
  };

  const outcome = authorizeDeployment(authInput);

  if (!outcome.ok) {
    return {
      ok: false,
      outcome: outcome as DeploymentAuthorizationOutcomeV1 & { ok: false },
      gateDecision,
    };
  }

  return {
    ok: true,
    outcome: outcome as DeploymentAuthorizationOutcomeV1 & { ok: true },
    gateDecision,
  };
}

export async function verifyDurableSync(
  artifactHash: Sha256Digest,
  r2Config: R2StorageConfig,
): Promise<boolean> {
  const adapter = createR2StorageAdapter(r2Config);
  const result = await verifyStoredObject(adapter, artifactHash);
  return result.ok && result.verified;
}

export async function authorizeMainPromotion(
  gateDecisionPath: string,
  mainVerificationPath: string,
  artifactHash: Sha256Digest,
  candidateId: string,
  durableSyncVerified: boolean,
  forceRequested: boolean,
  skipRequested: boolean,
  waiverRequested: boolean,
  graceRequested: boolean,
): Promise<{
  authorization: AuthorizeOutcome;
  mainVerification: MainVerificationOutcomeV1;
}> {
  const gateDecision = await loadGateDecision(gateDecisionPath);
  const mainVerificationDecision = await loadMainVerificationDecision(mainVerificationPath);

  const mainVerification = verifyMainPromotion({
    candidateId,
    mainVerificationDecision,
    durableSyncVerified,
    artifactHash,
    priorOperationRef: null,
  });

  if (!mainVerification.ok) {
    return {
      authorization: {
        ok: false,
        outcome: {
          ok: false,
          ruleId: mainVerification.ruleId,
          message: mainVerification.message,
          gate: "promote-main",
        },
        gateDecision,
      },
      mainVerification,
    };
  }

  const authInput: DeploymentAuthorizationInputV1 = {
    candidateId,
    gate: "promote-main",
    gateDecision,
    durableSyncVerified,
    artifactReadinessVerified: true,
    artifactHash,
    forceRequested,
    skipRequested,
    waiverRequested,
    graceRequested,
  };

  const outcome = authorizeDeployment(authInput);

  if (!outcome.ok) {
    return {
      authorization: {
        ok: false,
        outcome: outcome as DeploymentAuthorizationOutcomeV1 & { ok: false },
        gateDecision,
      },
      mainVerification,
    };
  }

  return {
    authorization: {
      ok: true,
      outcome: outcome as DeploymentAuthorizationOutcomeV1 & { ok: true },
      gateDecision,
    },
    mainVerification,
  };
}

export async function evaluateRollbackRequest(
  input: RollbackEvaluationInputV1,
): Promise<RollbackEvaluationOutcomeV1> {
  return evaluateRollback(input);
}

export function buildEffectRecord(
  operationId: string,
  candidateId: string,
  gate: CertificationGate,
  channel: "dev" | "alt" | "main",
  artifactHash: Sha256Digest,
  decisionId: string,
  durableSyncVerified: boolean,
  mainVerificationDecisionId: string | null,
  state: DeploymentOperationState,
  timestamp: string,
  workerVersionId?: string,
  releaseId?: string,
): DeploymentEffectRecordV1 {
  return buildDeploymentEffectRecord(
    operationId,
    candidateId,
    gate,
    channel,
    artifactHash,
    decisionId,
    durableSyncVerified,
    mainVerificationDecisionId,
    state,
    timestamp,
    workerVersionId,
    releaseId,
  );
}

export async function writeDeploymentEffectRecord(
  cacheCloneDir: string,
  record: DeploymentEffectRecordV1,
  deploymentUrl?: string,
  workerVersionId?: string,
  releaseId?: string,
): Promise<string> {
  const dir = path.join(cacheCloneDir, "deployment-operations");
  await fs.mkdir(dir, { recursive: true });
  const filePath = path.join(dir, `${record.operationId}.json`);
  let payload: Record<string, unknown> = { ...record };
  if (deploymentUrl) payload = { ...payload, deploymentUrl };
  if (workerVersionId) payload = { ...payload, workerVersionId };
  if (releaseId) payload = { ...payload, releaseId };
  await writeFileIfChanged(filePath, JSON.stringify(payload, null, 2) + "\n");

  const relPath = path.join("deployment-operations", `${record.operationId}.json`);
  try {
    gitExec(cacheCloneDir, `add ${relPath}`);
    cacheCloneCommit(
      cacheCloneDir,
      `deployment-operations: ${record.operationId} (${record.state})`,
    );
    const branch = gitExec(cacheCloneDir, "rev-parse --abbrev-ref HEAD").trim();
    gitExec(cacheCloneDir, `push origin ${branch}`);
  } catch {
    // Best-effort commit+push — file is written, sync will propagate later
  }

  return filePath;
}

export function makeR2ConfigFromEnv(
  env: Record<string, string | undefined>,
): R2StorageConfig | null {
  const accountId = env.R2_ACCOUNT_ID;
  const accessKeyId = env.R2_ACCESS_KEY_ID;
  const secretAccessKey = env.R2_SECRET_ACCESS_KEY;
  const bucketName = env.R2_BUCKET_NAME;
  const apiToken = env.R2_API_TOKEN ?? env.CLOUDFLARE_API_TOKEN;

  if (!accountId || !accessKeyId || !secretAccessKey || !bucketName) {
    return null;
  }

  return { accountId, accessKeyId, secretAccessKey, bucketName, apiToken };
}

export function resolveGateDecisionPath(
  cacheCloneDir: string,
  releaseId: string,
  gate: "dev" | "alt" | "main",
  override?: string,
): string {
  if (override) return override;
  return path.join(cacheCloneDir, "gate-decisions", `${releaseId}-${gate}.json`);
}
