/*
<MODULE_CONTRACT>
<purpose>
RFC-0840: Persist and restore root-level operator config files between mission workpiece and cache clone.
Provides persistOperatorConfigFiles (mission.close) and restoreOperatorConfigFiles (mission.materialize).
Follows the same pattern as env-persist.ts (RFC-0822) but for non-env operator config files.
</purpose>
<non-goals>
  <item>Do not git-commit operator config files — they are untracked artifacts in the cache clone.</item>
  <item>Do not modify file contents during restore — unlike env restoration which rewrites PUBLIC_IMAGE_PROVIDER.</item>
  <item>Do not add generated build outputs to OPERATOR_CONFIG_FILES — those are regenerated by build.prepare.</item>
  <item>Do not add .env* files — those are already handled by RFC-0822.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>RFC-0840: initial operator-config-files module with OPERATOR_CONFIG_FILES, persistOperatorConfigFiles, and restoreOperatorConfigFiles.</item>
</CHANGE_SUMMARY>
*/

import fs from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";

export interface OperatorConfigPersistResult {
  copied: string[];
  skipped: string[];
}

export const OPERATOR_CONFIG_FILES = [
  ".lighthouse-budget-ignore",
  "src/image-delivery.config.yaml",
] as const;

export async function persistOperatorConfigFiles(
  workpieceDir: string,
  cacheCloneDir: string,
): Promise<OperatorConfigPersistResult> {
  const copied: string[] = [];
  const skipped: string[] = [];

  for (const entry of OPERATOR_CONFIG_FILES) {
    const src = path.join(workpieceDir, entry);
    const dest = path.join(cacheCloneDir, entry);
    if (!existsSync(src)) continue;
    try {
      await fs.mkdir(path.dirname(dest), { recursive: true });
      await fs.copyFile(src, dest);
      copied.push(entry);
    } catch {
      skipped.push(entry);
    }
  }

  return { copied, skipped };
}

export async function restoreOperatorConfigFiles(
  cacheCloneDir: string,
  workpieceDir: string,
): Promise<OperatorConfigPersistResult> {
  const copied: string[] = [];
  const skipped: string[] = [];

  for (const entry of OPERATOR_CONFIG_FILES) {
    const src = path.join(cacheCloneDir, entry);
    const dest = path.join(workpieceDir, entry);
    if (!existsSync(src)) continue;
    try {
      await fs.mkdir(path.dirname(dest), { recursive: true });
      await fs.copyFile(src, dest);
      copied.push(entry);
    } catch {
      skipped.push(entry);
    }
  }

  return { copied, skipped };
}
